### ISSUE TITLE
请问这个生成器如何使用

### ISSUE THREAD

**Issue by ZhangHouhou** [guxingke/pages#1]

**Comment by guxingke** [comment]
这个 issue 也没有提示我. 

暂时没有文档说明如何使用. 
简而言之, 
1. 必须是 unix* 系统.
2. 安装必要依赖, pandoc, yq, coreutils. 

3.  fork 或者 download 项目
4. 删除 src/post/ , src/page/ 下文件. 
5. make  构建
6. make serve  预览.

**Comment by briteming** [comment]
hi。

在debian vps上，如何安装yq, coreutils？
安装命令是什么？
谢谢回复！
